import{motion,AnimatePresence}from'framer-motion'
import{useApp}from'../../hooks/useAppState'
const platforms=[{name:'WhatsApp',icon:'💬',c:'#25D366'},{name:'Telegram',icon:'✈️',c:'#0088CC'},{name:'X',icon:'𝕏',c:'#000'},{name:'Instagram',icon:'📸',c:'#E4405F'},{name:'Copy Link',icon:'🔗',c:'#8E8E93'},{name:'More',icon:'•••',c:'#636366'}]
export function ShareSheet(){
  const{showShare,setShowShare,shareData}=useApp()
  return <AnimatePresence>{showShare&&<><motion.div initial={{opacity:0}} animate={{opacity:1}} exit={{opacity:0}} onClick={()=>setShowShare(false)} className="fixed inset-0 z-50" style={{background:'rgba(0,0,0,.4)'}}/><motion.div initial={{y:300}} animate={{y:0}} exit={{y:300}} transition={{type:'spring',damping:25,stiffness:300}} className="fixed bottom-0 left-0 right-0 z-50" style={{maxWidth:390,margin:'0 auto'}}><div style={{background:'#fff',borderRadius:'20px 20px 0 0',padding:'16px 16px 40px'}}><div className="flex justify-between items-center mb-4"><h3 className="text-[18px] font-bold">Share Verification</h3><button onClick={()=>setShowShare(false)} className="press-scale" style={{width:30,height:30,borderRadius:15,background:'rgba(60,60,67,.06)',display:'flex',alignItems:'center',justifyContent:'center'}}><svg width="10" height="10" viewBox="0 0 12 12" fill="none"><path d="M2 2l8 8M10 2L2 10" stroke="#8E8E93" strokeWidth="1.8" strokeLinecap="round"/></svg></button></div>{shareData&&<div className="mb-4" style={{padding:'12px 14px',borderRadius:12,background:'#F7F3ED'}}><p className="text-[14px] font-semibold">{shareData.title}</p><p className="text-[12px] mt-1" style={{color:'#8E8E93'}}>{shareData.text.slice(0,80)}...</p></div>}<div className="grid grid-cols-3 gap-4">{platforms.map(p=><button key={p.name} onClick={()=>setShowShare(false)} className="flex flex-col items-center gap-2 press-scale"><div className="flex items-center justify-center" style={{width:52,height:52,borderRadius:16,background:`${p.c}12`}}><span className="text-[24px]">{p.icon}</span></div><span className="text-[11px] font-medium">{p.name}</span></button>)}</div></div></motion.div></>}</AnimatePresence>
}
export function ToastBar(){
  const{toast,setToast}=useApp()
  return <AnimatePresence>{toast&&<motion.div initial={{y:-60,opacity:0}} animate={{y:0,opacity:1}} exit={{y:-60,opacity:0}} onAnimationComplete={()=>setTimeout(()=>setToast(''),1800)} className="fixed top-[60px] left-0 right-0 z-50 flex justify-center" style={{maxWidth:390,margin:'0 auto'}}><div className="flex items-center gap-2 px-5 py-3 shadow-lg" style={{borderRadius:14,background:'#0F0F0C'}}><svg width="16" height="16" viewBox="0 0 24 24" fill="#34C759"><path d="M9 12l2 2 4-4m6 2a9 9 0 11-18 0 9 9 0 0118 0z"/></svg><span className="text-[14px] font-semibold text-white">{toast}</span></div></motion.div>}</AnimatePresence>
}
