import{useNavigate,useParams}from'react-router-dom';import{motion}from'framer-motion';import{Page,NavBar,HeroCard,SectionHead}from'../ui';import{gradeConfigs,type Grade}from'../../data/mock';import{getChainByHadith}from'../../data/database'
export default function ChainScreen(){const nav=useNavigate();const{grade='sahih'}=useParams();const g=gradeConfigs[grade as Grade]||gradeConfigs.sahih;const chain=getChainByHadith('h1')
  const relColors:Record<string,{c:string,bg:string}>={infallible:{c:'#C9A24D',bg:'rgba(201,162,77,.12)'},trustworthy:{c:'#3E7C59',bg:'#E8F9ED'},reliable:{c:'#2B6CB8',bg:'rgba(59,125,216,.08)'},weak:{c:'#C94A4A',bg:'#FFF0EF'},unknown:{c:'#8E8E93',bg:'#F2F2F7'}}
  return <Page><NavBar title="Transmission Chain"/>
    <HeroCard gradient={g.gradient} label="Chain of Narration" labelColor={g.secondaryColor} title={`${chain.length} Narrators`} subtitle="Complete chain from Prophet ﷺ to compiler" icon={<svg width="16" height="16" viewBox="0 0 24 24" fill={g.secondaryColor}><path d="M9 12l2 2 4-4m6 2a9 9 0 11-18 0 9 9 0 0118 0z"/></svg>}/>
    <div className="flex gap-2 px-4 mt-3">{[['Continuity','Connected','#3E7C59'],['Reliability','Strong','#3E7C59'],['Consensus','Agreed','#3E7C59']].map(([l,v,c])=><div key={l} className="flex-1 bg-white text-center" style={{borderRadius:12,padding:'12px 8px'}}><p className="text-[10px] font-bold uppercase" style={{color:'#8E8E93'}}>{l}</p><p className="text-[14px] font-bold mt-1" style={{color:c}}>{v}</p></div>)}</div>
    <SectionHead title="Narrator Lineage" color={g.accentColor}/>
    <div className="px-4 pb-8">{chain.map((n,i)=>{const rc=relColors[n.reliability]||relColors.unknown;return<div key={n.id}><motion.div initial={{opacity:0,y:10}} animate={{opacity:1,y:0}} transition={{delay:i*.1}} className="bg-white flex items-center gap-3 press-scale" style={{borderRadius:14,padding:'14px 16px',border:i===0?'1.5px solid rgba(201,162,77,.3)':'1px solid rgba(60,60,67,.04)'}}>
      <div className="shrink-0 flex items-center justify-center text-[14px] font-bold" style={{width:42,height:42,borderRadius:21,background:rc.bg,color:rc.c}}>{n.name[0]==='P'?'ﷺ':n.name[0]}</div>
      <div className="flex-1"><p className="text-[15px] font-semibold">{n.name}</p><p className="font-arabic text-[13px] mt-0.5" style={{color:'#8E8E93'}}>{n.arabic_name}</p></div>
      <div className="text-right"><span className="text-[10px] font-bold px-2 py-0.5 rounded-full" style={{background:rc.bg,color:rc.c}}>{n.reliability}</span><p className="text-[10px] mt-1" style={{color:'#AEAEB2'}}>{n.era}</p></div>
    </motion.div>{i<chain.length-1&&<div className="flex justify-center py-1"><div style={{width:2,height:20,borderRadius:1,background:'linear-gradient(180deg,rgba(201,162,77,.3),rgba(201,162,77,.1))'}}/></div>}</div>})}</div></Page>}
