import{useNavigate}from'react-router-dom';import{motion}from'framer-motion';import{getBadgeStyle}from'../../data/mock';import{Page,TabBar,CardGroup,Cell}from'../ui';import{useApp}from'../../hooks/useAppState'
const items=[{id:'r1',icon:'🎙️',iconBg:'#FFF8ED',title:'Surah Al-Fatiha Recitation',excerpt:'In the name of Allah…',grade:'pending' as const,time:'2m'},{id:'r2',icon:'📜',iconBg:'#FDF8ED',title:'Sahih Al-Bukhari 1',excerpt:'Actions judged by intentions…',grade:'sahih' as const,time:'4h'},{id:'r3',icon:'🎓',iconBg:'#E8F9ED',title:'Surah Al-Haqqah',excerpt:'Book given on the right hand…',grade:'sahih' as const,time:'6h'}]
export default function HomeScreen(){const nav=useNavigate();const{currentUser}=useApp();const initials=(currentUser?.username||'AA').slice(0,2).toUpperCase()
  return <Page><div style={{paddingBottom:90}}>
    <header className="flex items-center justify-between" style={{padding:'8px 16px 0'}}><div className="flex items-center gap-2.5"><div className="flex items-center justify-center" style={{width:38,height:38,borderRadius:10,background:'linear-gradient(145deg,#D4AD4E,#E6C05C)'}}><svg width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="#fff" strokeWidth="2.5" strokeLinecap="round"><path d="M12 2v20M8 5v14M4 8v8M16 5v14M20 8v8"/></svg></div><span className="font-serif text-[22px] font-bold">Qisah</span></div><button onClick={()=>nav('/profile')} className="flex items-center justify-center text-[14px] font-bold press-scale" style={{width:38,height:38,borderRadius:19,background:'linear-gradient(135deg,rgba(230,182,92,.25),rgba(201,162,77,.15))',border:'2px solid rgba(201,162,77,.25)',color:'#C9A24D'}}>{initials}</button></header>
    <div className="text-center" style={{padding:'20px 28px 4px'}}><h1 className="font-serif text-[28px] font-bold" style={{lineHeight:1.15}}>What are you<br/>listening to?</h1><p className="text-[15px] mt-2" style={{color:'#8E8E93'}}>Scan a clip for authentic context</p></div>
    <div className="flex justify-center" style={{padding:'12px 0 8px'}}><motion.button whileTap={{scale:.92}} onClick={()=>nav('/scan')} className="relative" style={{width:160,height:160}}><div className="absolute rounded-full" style={{width:160,height:160,border:'1px solid rgba(201,162,77,.1)'}}/><div className="absolute rounded-full" style={{width:130,height:130,border:'1px solid rgba(201,162,77,.18)',left:15,top:15}}/><div className="absolute rounded-full" style={{width:104,height:104,border:'1px solid rgba(201,162,77,.25)',left:28,top:28}}/><div className="absolute flex items-center justify-center" style={{width:88,height:88,borderRadius:44,left:36,top:36,background:'linear-gradient(145deg,#D4AD4E,#E6C05C)',boxShadow:'0 6px 24px rgba(201,162,77,.3)'}}><svg width="34" height="34" viewBox="0 0 24 24" fill="none" stroke="#fff" strokeWidth="1.8" strokeLinecap="round"><rect x="9" y="1" width="6" height="12" rx="3"/><path d="M5 10a7 7 0 0014 0M12 17v4M8 21h8"/></svg></div></motion.button></div>
    <div className="px-4 mb-3"><button onClick={()=>nav('/paste-link')} className="flex items-center gap-3 bg-white w-full text-left press-scale" style={{borderRadius:14,padding:'14px 16px',border:'1.5px dashed rgba(201,162,77,.25)'}}><div className="shrink-0 flex items-center justify-center" style={{width:38,height:38,borderRadius:10,background:'#FDF8ED'}}><svg width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="#C9A24D" strokeWidth="2"><path d="M10 13a5 5 0 007.54.54l3-3a5 5 0 00-7.07-7.07l-1.72 1.71"/><path d="M14 11a5 5 0 00-7.54-.54l-3 3a5 5 0 007.07 7.07l1.71-1.71"/></svg></div><div className="flex-1"><p className="text-[16px] font-semibold">Paste a link to verify</p><p className="text-[13px] mt-0.5" style={{color:'#8E8E93'}}>Paste any video or audio link</p></div><svg width="7" height="12" viewBox="0 0 7 12" fill="none"><path d="M1 1l5 5-5 5" stroke="#C7C7CC" strokeWidth="1.5" strokeLinecap="round" strokeLinejoin="round"/></svg></button></div>
    <div className="flex gap-2 px-4 mb-5">{[{l:'Quran',c:'#145229',bg:'#E8F9ED'},{l:'Hadith',c:'#8B6D1F',bg:'#FDF8ED'},{l:'Text',c:'#636366',bg:'#F2F2F7'}].map(ch=><button key={ch.l} onClick={()=>nav('/scan')} className="flex-1 flex items-center justify-center gap-2 press-scale" style={{padding:'10px 6px',borderRadius:12,background:ch.bg,minHeight:44}}><span className="text-[14px] font-semibold" style={{color:ch.c}}>{ch.l}</span></button>)}</div>
    <div className="px-4"><div className="flex justify-between items-center mb-2"><h2 className="text-[18px] font-bold">Recent Verifications</h2><button onClick={()=>nav('/library')} className="text-[15px] font-medium" style={{color:'#007AFF'}}>See All</button></div>
      <CardGroup>{items.map((r,i)=>{const s=getBadgeStyle(r.grade);return <Cell key={r.id} icon={r.icon} iconBg={r.iconBg} title={r.title} subtitle={<><span className="text-[13px]" style={{color:'#8E8E93'}}>{r.excerpt}</span><br/><span className="inline-flex items-center rounded-full text-[11px] font-semibold px-2.5 py-[2px] mt-1" style={{color:s.color,background:s.bg}}>{s.label}</span><span className="text-[11px] ml-1.5" style={{color:'#AEAEB2'}}>{r.time}</span></>} last={i===items.length-1} onTap={()=>nav('/result/sahih')}/>})}</CardGroup></div>
  </div><TabBar active="home"/></Page>}
