import{useState}from'react';import{useNavigate}from'react-router-dom';import{motion}from'framer-motion';import{madhabOptions}from'../../data/mock';import{Page}from'../ui';import{useApp}from'../../hooks/useAppState'
export default function MadhabScreen(){const[sel,setSel]=useState('shafii');const nav=useNavigate();const{setMadhab}=useApp()
  const go=()=>{setMadhab(sel);nav('/signup')}
  return <Page><nav className="flex items-center justify-between px-4" style={{height:44}}><button onClick={()=>nav(-1)} className="text-[17px]" style={{color:'#007AFF',minHeight:44}}>‹ Back</button><span className="text-[17px] font-semibold">Preferences</span><button onClick={()=>nav('/signup')} className="text-[15px]" style={{color:'#007AFF',minHeight:44}}>Skip</button></nav>
    <div style={{padding:'20px 24px 0'}}><h1 className="font-serif text-[28px] font-bold" style={{lineHeight:'34px'}}>Choose your preferred<br/>school of thought</h1><p className="text-[15px] mt-2" style={{color:'#636366',lineHeight:'22px'}}>This will be highlighted first in verification results. You can change this anytime in Settings.</p></div>
    <div style={{padding:'20px 16px 0'}}>{madhabOptions.map(m=>{const a=sel===m.id;return <motion.button key={m.id} whileTap={{scale:.98}} onClick={()=>setSel(m.id)} className="w-full flex items-center gap-3.5 mb-2 text-left" style={{background:'#fff',borderRadius:14,padding:'16px 18px',border:a?'2px solid #C9A24D':'1.5px solid rgba(60,60,67,.08)'}}>
      <div className="shrink-0 flex items-center justify-center" style={{width:44,height:44,borderRadius:22,background:m.bgColor}}><span className="text-[18px] font-bold" style={{color:m.color}}>{m.initial}</span></div>
      <div className="flex-1"><p className="text-[17px] font-semibold">{m.name}</p><p className="text-[13px] mt-0.5" style={{color:'#8E8E93'}}>{m.scholar} · {m.region}</p></div>
      <div className="shrink-0" style={{width:24,height:24,borderRadius:12,background:a?'#C9A24D':'transparent',border:a?'none':'1.5px solid #D1D1D6',display:'flex',alignItems:'center',justifyContent:'center'}}>{a&&<svg width="12" height="12" viewBox="0 0 24 24" fill="none" stroke="#fff" strokeWidth="3"><path d="M5 12l5 5L20 7"/></svg>}</div></motion.button>})}</div>
    <div className="flex-1" style={{minHeight:40}}/>
    <div style={{padding:'0 32px 24px'}}><button onClick={go} className="w-full press-scale flex items-center justify-center" style={{height:52,borderRadius:14,background:'linear-gradient(135deg,#C9A24D,#E6B65C)',border:'none'}}><span className="text-[17px] font-semibold text-white">Continue</span></button><p className="text-center text-[13px] mt-3" style={{color:'#AEAEB2'}}>You can change this anytime in Settings</p></div></Page>}
