import{useState}from'react';import{useNavigate}from'react-router-dom';import{motion,AnimatePresence}from'framer-motion';import{Page}from'../ui'
const slides=[{title:'Verify Islamic\nKnowledge Instantly',desc:'Capture audio, video, or text to receive authentic sources and context you can trust',btn:'Continue'},{title:'Authentic Hadith\nReferences',desc:'Every verification is backed by scholarly sources. Access original texts, grading, and chain of narration.',btn:'Continue'},{title:'Scholar Identification\n& Full Sources',desc:'Gain access to detailed scholarly opinions across all major schools of thought. Complete peace of mind.',btn:'Start Verifying'}]
export default function OnboardingScreen(){const[s,setS]=useState(0);const nav=useNavigate();const sl=slides[s];const next=()=>{if(s>=2)nav('/madhab');else setS(s+1)}
  return <Page className="h-full flex flex-col"><div style={{height:54}}/>
    <div className="px-4"><div className="w-full overflow-hidden relative flex items-center justify-center" style={{height:260,borderRadius:24,background:s<2?'linear-gradient(155deg,#1B6B3A,#2D8F4E)':'linear-gradient(155deg,#7A2828,#4A1818)'}}><div className="geo-pattern" style={{opacity:.07}}/>
      <AnimatePresence mode="wait"><motion.div key={s} initial={{opacity:0,scale:.9}} animate={{opacity:1,scale:1}} exit={{opacity:0}} className="relative z-10 text-center">
        <span className="text-[56px]">{['📖','📜','🎓'][s]}</span>
        <div className="absolute bottom-[-20px] right-[-40px] bg-white flex items-center gap-1.5 shadow-lg" style={{borderRadius:12,padding:'8px 14px'}}><svg width="14" height="14" viewBox="0 0 24 24" fill="#3E7C59"><path d="M9 12l2 2 4-4m6 2a9 9 0 11-18 0 9 9 0 0118 0z"/></svg><div><p className="text-[11px] font-bold">Verified</p><p className="text-[9px]" style={{color:'#8E8E93'}}>Authentic source</p></div></div>
      </motion.div></AnimatePresence></div></div>
    <div className="flex-1 flex flex-col items-center" style={{padding:'32px 32px 0'}}>
      <AnimatePresence mode="wait"><motion.div key={s} initial={{y:8,opacity:0}} animate={{y:0,opacity:1}} exit={{opacity:0}} className="text-center">
        <h1 className="font-serif text-[28px] font-bold" style={{lineHeight:1.2,whiteSpace:'pre-line'}}>{sl.title}</h1>
        <p className="text-[16px] mt-4" style={{color:'#636366',lineHeight:1.55,maxWidth:320}}>{sl.desc}</p>
      </motion.div></AnimatePresence>
      <div className="flex items-center gap-4 mt-8"><div className="flex gap-1.5">{[0,1,2].map(i=><div key={i} style={{width:i===s?24:8,height:8,borderRadius:4,background:i===s?'#C9A24D':'rgba(201,162,77,.2)',transition:'all .3s'}}/>)}</div><div style={{width:1,height:14,background:'#D1D1D6'}}/><button onClick={()=>nav('/madhab')} className="text-[15px]" style={{color:'#8E8E93',minHeight:44}}>Skip</button></div></div>
    <div style={{padding:'0 24px 24px'}}><button onClick={next} className="w-full flex items-center justify-center gap-2 press-scale" style={{height:52,borderRadius:14,background:'linear-gradient(135deg,#C9A24D,#E6B65C)',border:'none'}}><span className="text-[17px] font-semibold text-white">{sl.btn}</span><svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="#fff" strokeWidth="2.5" strokeLinecap="round"><path d="M5 12h14M12 5l7 7-7 7"/></svg></button>
      <div className="text-center mt-4"><span className="text-[14px]" style={{color:'#8E8E93'}}>Already have an account? </span><button onClick={()=>nav('/signup')} className="text-[14px] font-semibold" style={{color:'#007AFF'}}>sign in</button></div></div></Page>}
