import{useNavigate}from'react-router-dom';import{premiumFeatures}from'../../data/mock';import{Page}from'../ui';import{useApp}from'../../hooks/useAppState';import{getPricing}from'../../data/database'
export default function PaywallScreen(){const nav=useNavigate();const{setPro}=useApp();const p=getPricing('NG')
  return <Page bg="#0F0F0C"><div className="relative min-h-full"><div className="geo-pattern" style={{opacity:.04}}/><div className="relative z-10">
    <div className="flex justify-end" style={{padding:'10px 16px'}}><button onClick={()=>nav(-1)} className="press-scale" style={{width:30,height:30,borderRadius:15,background:'rgba(255,255,255,.08)',display:'flex',alignItems:'center',justifyContent:'center',border:'none'}}><svg width="10" height="10" viewBox="0 0 12 12" fill="none"><path d="M2 2l8 8M10 2L2 10" stroke="#8E8E93" strokeWidth="1.8" strokeLinecap="round"/></svg></button></div>
    <div className="text-center" style={{padding:'8px 32px 24px'}}><div className="inline-flex items-center justify-center mb-3" style={{width:72,height:72,borderRadius:20,background:'linear-gradient(145deg,#D4AD4E,#E6C05C)',boxShadow:'0 10px 28px rgba(201,162,77,.3)'}}><svg width="32" height="32" viewBox="0 0 24 24" fill="none" stroke="#fff" strokeWidth="2.5" strokeLinecap="round"><path d="M12 2v20M8 5v14M4 8v8M16 5v14M20 8v8"/></svg></div><p className="text-[11px] font-bold uppercase tracking-[2px] mb-2" style={{color:'#C9A24D'}}>Qisah Pro</p><h1 className="font-serif text-[26px] font-bold text-white" style={{lineHeight:1.2}}>Unlock the full depth<br/>of Islamic Knowledge</h1><p className="text-[14px] mt-2" style={{color:'#8B8680',lineHeight:1.5}}>Advanced research tools, deeper analysis,<br/>and scholarly collections</p></div>
    <div className="px-4 mb-4">{premiumFeatures.map((f,i)=><div key={i} className="flex items-center gap-3" style={{padding:'14px 0',borderBottom:'.33px solid rgba(255,255,255,.04)'}}><div className="shrink-0 flex items-center justify-center text-[18px]" style={{width:38,height:38,borderRadius:19,background:'rgba(201,162,77,.1)'}}>{f.icon}</div><div><p className="text-[16px] font-semibold text-white">{f.title}</p><p className="text-[13px]" style={{color:'#8B8680'}}>{f.desc}</p></div></div>)}</div>
    <div className="px-4"><div className="press-scale mb-2.5" style={{borderRadius:16,padding:'16px 18px',background:'rgba(201,162,77,.08)',border:'1.5px solid rgba(201,162,77,.25)'}}><div className="flex justify-between items-center"><div><span className="text-[10px] font-bold px-2 py-0.5 rounded-full" style={{background:'#C9A24D',color:'#0F0F0C'}}>Best value</span><p className="text-[18px] font-semibold text-white mt-2">Annual</p><p className="text-[12px]" style={{color:'#8B8680'}}>{p.symbol}{(p.annualMonthly).toLocaleString()}/month billed yearly</p></div><div className="text-right"><p className="text-[28px] font-bold" style={{color:'#C9A24D'}}>{p.symbol}{p.annual.toLocaleString()}</p><p className="text-[11px]" style={{color:'#8B8680'}}>per year</p></div></div></div>
      <div className="press-scale mb-4" style={{borderRadius:16,padding:'16px 18px',background:'rgba(255,255,255,.04)',border:'1px solid rgba(255,255,255,.05)'}}><div className="flex justify-between items-center"><div><p className="text-[16px] font-semibold text-white">Monthly</p><p className="text-[12px]" style={{color:'#8B8680'}}>Cancel anytime</p></div><p className="text-[22px] font-bold text-white">{p.symbol}{p.monthly.toLocaleString()}<span className="text-[12px] font-normal" style={{color:'#8B8680'}}>/mo</span></p></div></div>
      <button onClick={()=>{setPro(true);nav('/home')}} className="w-full press-scale flex items-center justify-center" style={{height:52,borderRadius:14,background:'linear-gradient(135deg,#C9A24D,#E6B65C)',border:'none'}}><span className="text-[17px] font-semibold text-white">Start 7 Day Free Trial</span></button>
      <p className="text-center text-[12px] mt-3 pb-6" style={{color:'#6B6560'}}>Restore purchase · Terms · Privacy</p></div>
  </div></div></Page>}
