import{useState,useEffect}from'react';import{useNavigate}from'react-router-dom';import{motion}from'framer-motion';import{Page,NavBar,CardGroup,Cell}from'../ui'
const phases=['Listening...','Detecting speech...','Matching sources...','Verifying...']
export default function ScanScreen(){const nav=useNavigate();const[p,setP]=useState(0);const[t,setT]=useState('')
  useEffect(()=>{const t1=setTimeout(()=>{setP(1);setT('"... with hardship comes ease, verily with hardship comes ease..."')},1200);const t2=setTimeout(()=>setP(2),2500);const t3=setTimeout(()=>setP(3),3800);const t4=setTimeout(()=>nav('/result/quran'),5200);return()=>{clearTimeout(t1);clearTimeout(t2);clearTimeout(t3);clearTimeout(t4)}},[nav])
  return <Page><NavBar title="Verification Assistant" left="close" onClose={()=>nav('/home')}/>
    <div className="flex justify-center" style={{padding:'28px 0 12px'}}><div className="relative" style={{width:140,height:140}}><motion.div animate={{scale:[1,1.12,1]}} transition={{repeat:Infinity,duration:2}} className="absolute inset-0 rounded-full" style={{border:'1.5px solid rgba(201,162,77,.15)'}}/><div className="absolute flex items-center justify-center" style={{width:100,height:100,borderRadius:50,left:20,top:20,background:'linear-gradient(145deg,#D4AD4E,#E6C05C)',boxShadow:'0 6px 20px rgba(201,162,77,.3)'}}><span className="text-[40px]">🎙️</span></div></div></div>
    <div className="text-center px-8"><h2 className="text-[24px] font-bold">{phases[p]}</h2><p className="text-[15px] mt-1" style={{color:'#8E8E93'}}>Capturing audio to verify context</p></div>
    {t&&<motion.div initial={{opacity:0,y:8}} animate={{opacity:1,y:0}} className="mx-4 mt-5 bg-white" style={{borderRadius:14,padding:'16px 18px'}}><p className="text-[11px] font-bold uppercase tracking-wider mb-2" style={{color:'#C9A24D'}}>Detecting</p><p className="font-serif text-[15px] italic" style={{color:'#2A2A24',lineHeight:1.6}}>{t}</p></motion.div>}
    <div className="flex gap-1.5 mx-4 mt-5">{[0,1,2,3].map(i=><div key={i} className="flex-1 rounded-full" style={{height:4,background:i<=p?'#C9A24D':'rgba(201,162,77,.12)',transition:'background .3s'}}/>)}</div>
    <div className="flex justify-center mt-4"><div className="flex items-center gap-1.5 px-4 py-2 rounded-full" style={{background:'#E8F9ED'}}><svg width="14" height="14" viewBox="0 0 24 24" fill="#3E7C59"><path d="M9 12l2 2 4-4m6 2a9 9 0 11-18 0 9 9 0 0118 0z"/></svg><span className="text-[12px] font-semibold" style={{color:'#145229'}}>Secure on device processing</span></div></div>
    <div style={{padding:'24px 16px 0'}}><div className="flex items-center gap-2 mb-2"><div style={{width:3,height:18,borderRadius:1.5,background:'#C9A24D'}}/><h2 className="text-[18px] font-bold">Other Capture Options</h2></div>
      <CardGroup><Cell icon="🎬" iconBg="#FFEDEC" title="Record Video" subtitle="For clips and lectures" onTap={()=>{}}/><Cell icon="🖼️" iconBg="#FFF8ED" title="Upload from Gallery" subtitle="Select media files" onTap={()=>{}}/><Cell icon="✍️" iconBg="#FDF8ED" title="Enter Text Manually" subtitle="Type or paste to verify" last onTap={()=>{}}/></CardGroup></div></Page>}
