import{useNavigate}from'react-router-dom';import{Page,TabBar,CardGroup,Cell}from'../ui';import{useApp}from'../../hooks/useAppState'
export default function SettingsScreen(){const nav=useNavigate();const{isDark,toggleDark,notifications,toggleNotifications,madhab,saved,isPro,currentUser}=useApp()
  const mName:Record<string,string>={shafii:"Shafi'i",hanafi:'Hanafi',maliki:'Maliki',hanbali:'Hanbali'}
  const Tog=({on,f}:{on:boolean;f:()=>void})=><button onClick={f} className="shrink-0" style={{width:51,height:31,borderRadius:16,background:on?'#34C759':'rgba(120,120,128,.16)',padding:2,transition:'all .2s'}}><div style={{width:27,height:27,borderRadius:13.5,background:'#fff',boxShadow:'0 3px 8px rgba(0,0,0,.15)',marginLeft:on?20:0,transition:'margin-left .2s'}}/></button>
  const uname=currentUser?.username||'ahmed_ali'
  return <Page><div style={{paddingBottom:90}}><div style={{padding:'2px 16px 12px'}}><h1 className="text-[34px] font-bold">Settings</h1></div>
    <div className="px-4 mb-4"><button onClick={()=>nav('/profile')} className="w-full bg-white flex items-center gap-3.5 text-left press-scale" style={{borderRadius:14,padding:16}}><div className="shrink-0 flex items-center justify-center font-serif text-[22px] font-bold" style={{width:60,height:60,borderRadius:30,background:'linear-gradient(135deg,rgba(230,182,92,.2),rgba(201,162,77,.12))',border:'2px solid rgba(201,162,77,.2)',color:'#8B6D1F'}}>{uname[0].toUpperCase()}{uname[1]?.toUpperCase()}</div><div className="flex-1"><p className="text-[18px] font-semibold">{uname}</p><p className="text-[13px] mt-0.5" style={{color:'#8E8E93'}}>{currentUser?.email||'ahmed@example.com'}</p><div className="flex items-center gap-1 mt-1"><svg width="14" height="14" viewBox="0 0 24 24" fill="#3E7C59"><path d="M9 12l2 2 4-4m6 2a9 9 0 11-18 0 9 9 0 0118 0z"/></svg><span className="text-[12px] font-semibold" style={{color:'#3E7C59'}}>{isPro?'Pro Member':'Verified Member'}</span></div></div><svg width="7" height="12" viewBox="0 0 7 12" fill="none"><path d="M1 1l5 5-5 5" stroke="#C7C7CC" strokeWidth="1.5" strokeLinecap="round" strokeLinejoin="round"/></svg></button></div>
    <div className="flex gap-2 px-4 mb-5">{[['42','Verified','#3E7C59'],[String(saved.length),'Saved','#C9A24D'],['3','Reported','#636366']].map(([n,l,c])=><div key={l} className="flex-1 bg-white text-center" style={{borderRadius:14,padding:'12px 8px'}}><p className="text-[20px] font-bold" style={{color:c}}>{n}</p><p className="text-[11px] mt-0.5" style={{color:'#8E8E93'}}>{l}</p></div>)}</div>
    <div className="px-4 mb-5"><button onClick={()=>nav('/madhab')} className="w-full flex justify-between items-center press-scale" style={{borderRadius:14,padding:'14px 16px',background:'#FDF8ED',border:'1px solid rgba(201,162,77,.1)'}}><div><p className="text-[16px] font-semibold">Preferred Madhab</p><p className="text-[13px] mt-0.5" style={{color:'#8E8E93'}}>{mName[madhab]||"Shafi'i"} · Prioritized in results</p></div><svg width="7" height="12" viewBox="0 0 7 12" fill="none"><path d="M1 1l5 5-5 5" stroke="#C7C7CC" strokeWidth="1.5" strokeLinecap="round" strokeLinejoin="round"/></svg></button></div>
    <p className="text-[11px] font-bold uppercase tracking-wider px-4 mb-2" style={{color:'#8E8E93'}}>Preferences</p>
    <div className="px-4 mb-5"><CardGroup><Cell title="Language" right={<div className="flex items-center gap-1"><span className="text-[15px]" style={{color:'#8E8E93'}}>English</span><svg width="7" height="12" viewBox="0 0 7 12" fill="none"><path d="M1 1l5 5-5 5" stroke="#C7C7CC" strokeWidth="1.5" strokeLinecap="round" strokeLinejoin="round"/></svg></div>}/><Cell title="Notifications" right={<Tog on={notifications} f={toggleNotifications}/>}/><Cell title="Dark Mode" right={<Tog on={isDark} f={toggleDark}/>} last/></CardGroup></div>
    {!isPro&&<div className="px-4 mb-5"><button onClick={()=>nav('/paywall')} className="w-full press-scale flex items-center justify-center gap-2" style={{height:52,borderRadius:14,background:'linear-gradient(135deg,#C9A24D,#E6B65C)',border:'none'}}><span className="text-[17px] font-semibold text-white">Upgrade to Qisah Pro ✨</span></button></div>}
    <p className="text-[11px] font-bold uppercase tracking-wider px-4 mb-2" style={{color:'#8E8E93'}}>Support</p>
    <div className="px-4"><CardGroup><Cell icon="📖" iconBg="#E6F1FB" title="How Veri Works" onTap={()=>{}}/><Cell icon="📋" iconBg="#FDF8ED" title="Sources & Methodology" onTap={()=>{}}/><Cell icon="🏴" iconBg="#FFF0EF" title="Report an Issue" onTap={()=>{}}/><Cell icon="💬" iconBg="#E8F9ED" title="Feedback" last onTap={()=>{}}/></CardGroup></div>
    {currentUser?.email==='admin@qisah.app'&&<div className="px-4 mt-5"><button onClick={()=>nav('/admin')} className="w-full press-scale flex items-center justify-center" style={{height:44,borderRadius:12,background:'#0F0F0C',border:'none'}}><span className="text-[15px] font-semibold text-white">Admin Panel</span></button></div>}
  </div><TabBar active="settings"/></Page>}
