import{useEffect}from'react';import{useNavigate}from'react-router-dom';import{motion}from'framer-motion'
export default function SplashScreen(){const nav=useNavigate();useEffect(()=>{const t=setTimeout(()=>nav('/onboarding'),2800);return()=>clearTimeout(t)},[nav])
  return <div className="h-full flex flex-col items-center justify-center relative" style={{background:'var(--bg)'}}><div className="geo-pattern" style={{opacity:.02}}/>
    <motion.div initial={{scale:.85,opacity:0}} animate={{scale:1,opacity:1}} transition={{duration:.6}} className="relative z-10" style={{width:96,height:96,borderRadius:24,background:'linear-gradient(145deg,#D4AD4E,#E6C05C)',boxShadow:'0 16px 40px rgba(201,162,77,.25)'}}><div className="w-full h-full flex items-center justify-center"><svg width="44" height="44" viewBox="0 0 24 24" fill="none" stroke="#fff" strokeWidth="2.5" strokeLinecap="round"><path d="M12 2v20M8 5v14M4 8v8M16 5v14M20 8v8"/></svg></div></motion.div>
    <motion.h1 initial={{y:12,opacity:0}} animate={{y:0,opacity:1}} transition={{delay:.35}} className="font-serif text-[36px] font-bold mt-5 relative z-10">Qisah</motion.h1>
    <motion.p initial={{opacity:0}} animate={{opacity:1}} transition={{delay:.55}} className="font-arabic text-[22px] mt-1 relative z-10" style={{color:'#C9A24D'}}>قصاص</motion.p>
    <motion.div initial={{opacity:0}} animate={{opacity:1}} transition={{delay:1}} className="flex items-center gap-2.5 mt-10 relative z-10"><motion.div animate={{scale:[1,1.5,1]}} transition={{repeat:Infinity,duration:1.5}} style={{width:7,height:7,borderRadius:'50%',background:'#C9A24D'}}/><span className="text-[16px]" style={{color:'#8E8E93'}}>Retrieving verified Sources...</span></motion.div>
    <p className="absolute bottom-14 text-[11px] font-semibold uppercase tracking-[2px] z-10" style={{color:'#AEAEB2'}}>Powered by Veri</p>
    <p className="absolute bottom-8 text-[12px] z-10" style={{color:'#C7C7CC'}}>Sources updated Mar 9, 2026 v1.0</p></div>}
